name: Main Branch CI Workflow

on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master
      - feature

jobs:
  build:
    name: CI for Go
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'


      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Compile
        run: go build -v .

      - name: Unit Test
        run: go test -v ./...

      - name: Code Coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o coverage.html
        
      - name: Upload Code Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-out
          path: coverage.out

      - name: Upload Code Coverage HTML Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-html
          path: coverage.html


      - name: Static Code Analysis
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=sonarintegration-1
            -Dsonar.projectKey=sonarintegration-1_go-todo-project
            -Dsonar.sources=./
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.pullrequest.provider=GitHub
            -Dsonar.pullrequest.github.repository=${{ github.repository }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Send notification on Slack using Webhooks - Success
        if: ${{ always() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Go project built successfully."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification on Slack using Webhooks - Failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Go build failed. Please check the build logs for details."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


      - name: Download Code Coverage Artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-out
          path: ./coverage

      - name: Verify Code Coverage
        run: |
          COVERAGE=$(go tool cover -func=./coverage/coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          THRESHOLD=5.0
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "Code coverage is below threshold: $COVERAGE%"
            exit 1
          else
            echo "Code coverage is above threshold: $COVERAGE%"
          fi


      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
         JF_URL: ${{ secrets.JF_URL }}
         JF_USER: ${{ secrets.JF_USER }}
         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
         JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Ping JFrog Artifactory
        run: jf rt ping
        env:
         JF_URL: ${{ secrets.JF_URL }}
         JF_USER: ${{ secrets.JF_USER }}
         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
         JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Download, upload, and build artifacts
        run: |
         jf rt dl artifacts/
         jf rt u aether artifacts/
         jf rt bp
        env:
         JF_URL: ${{ secrets.JF_URL }}
         JF_USER: ${{ secrets.JF_USER }}
         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
         JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
